### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by XiYuan68** [JonathanRaiman/glove#1]
Tried to install the package on Fedora with
`pip3 install glove`
Got an error and failed: 

  Running setup.py install for glove ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-404sd2ni/glove/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-svzsl80g-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/glove
    copying glove/glove.py -> build/lib.linux-x86_64-3.6/glove
    copying glove/__init__.py -> build/lib.linux-x86_64-3.6/glove
    running egg_info
    writing glove.egg-info/PKG-INFO
    writing dependency_links to glove.egg-info/dependency_links.txt
    writing requirements to glove.egg-info/requires.txt
    writing top-level names to glove.egg-info/top_level.txt
    reading manifest file 'glove.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'glove.egg-info/SOURCES.txt'
    error: Error: setup script specifies an absolute path:
    
        /tmp/pip-build-404sd2ni/glove/glove/glove_inner.cpp
    
    setup() arguments must *always* be /-separated paths relative to the
    setup.py directory, *never* absolute paths.

**Is it a bug in the codes or my environment should be blamed?**

**Comment by jams777** [comment]
try~

command : pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip
`pip3 install `https://github.com/JonathanRaiman/glove/archive/master.zip`

install log.
Collecting https://github.com/JonathanRaiman/glove/archive/master.zip
  Downloading https://github.com/JonathanRaiman/glove/archive/master.zip
     - 10kB 44.9MB/s
Requirement already satisfied: cython in /usr/local/lib/python3.5/dist-packages (from glove==1.0.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from glove==1.0.1)
Installing collected packages: glove
  Running setup.py install for glove ... done
Successfully installed glove-1.0.1

**Comment by MichelleZLin** [comment]
@jams777 It works! Thank you. Do you happen to know the difference between version 1.0.1 and 1.0.2?

**Comment by martinrezk** [comment]
It also works for me. Any idea when this issue will be solved?

**Comment by seungwonpark** [comment]
Also experiencing installation error when using pip, but resolved with jans777's solution.
Anyway, pip installation issue should be solved. The error message I got looks like below.

My working environment is conda 4.5.4 (python 3.6.5) / Windows 10.

```
Collecting glove
  Downloading https://files.pythonhosted.org/packages/8a/c9/17c400d0c29746162bd47fc719bf3212b2b031949d41d712e9bdef11ae03/glove-1.0.2.tar.gz (44kB)
    100% |████████████████████████████████| 51kB 634kB/s mpy in c:\programdata\anaconda3\lib\site-packages (from glove) (1.14.3)
Building wheels for collected packages: glove
  Running setup.py bdist_wheel for glove ... error
  Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\veydp\\AppData\\Local\\Temp\\pip-install-r9fzyq18\\glove\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\veydp\AppData\Local\Temp\pip-wheel-7yde3gm4 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\glove
  copying glove\glove.py -> build\lib.win-amd64-3.6\glove
  copying glove\__init__.py -> build\lib.win-amd64-3.6\glove
  running egg_info
  writing glove.egg-info\PKG-INFO
  writing dependency_links to glove.egg-info\dependency_links.txt
  writing requirements to glove.egg-info\requires.txt
  writing top-level names to glove.egg-info\top_level.txt
  reading manifest file 'glove.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\veydp\AppData\Local\Temp\pip-install-r9fzyq18\glove\setup.py", line 85, in <module>
      include_package_data=True,
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 53, in run
      self.build_package_data()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 118, in build_package_data
      for package, src_dir, build_dir, filenames in self.data_files:
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 66, in __getattr__
      self.data_files = self._get_data_files()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 82, in _get_data_files
      self.analyze_manifest()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 138, in analyze_manifest
      self.run_command('egg_info')
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 278, in run
      self.find_sources()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 293, in find_sources
      mm.run()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 524, in run
      self.add_defaults()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 567, in add_defaults
      self.read_manifest()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
      self.filelist.append(line)
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 466, in append
      path = convert_path(item)
    File "C:\ProgramData\Anaconda3\lib\distutils\util.py", line 125, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/Users/jonathanraiman/Desktop/Coding/python_packages/glove/glove/glove_inner.cpp' cannot be absolute

  ----------------------------------------
  Failed building wheel for glove
  Running setup.py clean for glove
Failed to build glove
Installing collected packages: glove
  Running setup.py install for glove ... error
    Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\veydp\\AppData\\Local\\Temp\\pip-install-r9fzyq18\\glove\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\veydp\AppData\Local\Temp\pip-record-kwwro99h\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\glove
    copying glove\glove.py -> build\lib.win-amd64-3.6\glove
    copying glove\__init__.py -> build\lib.win-amd64-3.6\glove
    running egg_info
    writing glove.egg-info\PKG-INFO
    writing dependency_links to glove.egg-info\dependency_links.txt
    writing requirements to glove.egg-info\requires.txt
    writing top-level names to glove.egg-info\top_level.txt
    reading manifest file 'glove.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\veydp\AppData\Local\Temp\pip-install-r9fzyq18\glove\setup.py", line 85, in <module>
        include_package_data=True,
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 53, in run
        self.build_package_data()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 118, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 66, in __getattr__
        self.data_files = self._get_data_files()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 82, in _get_data_files
        self.analyze_manifest()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_py.py", line 138, in analyze_manifest
        self.run_command('egg_info')
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 278, in run
        self.find_sources()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 293, in find_sources
        mm.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 524, in run
        self.add_defaults()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 567, in add_defaults
        self.read_manifest()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
        self.filelist.append(line)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 466, in append
        path = convert_path(item)
      File "C:\ProgramData\Anaconda3\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/Users/jonathanraiman/Desktop/Coding/python_packages/glove/glove/glove_inner.cpp' cannot be absolute

    ----------------------------------------
Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\veydp\\AppData\\Local\\Temp\\pip-install-r9fzyq18\\glove\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\veydp\AppData\Local\Temp\pip-record-kwwro99h\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\veydp\AppData\Local\Temp\pip-install-r9fzyq18\glove\
```

**Comment by ilayaraja97** [comment]
As of today the pip install still doesn't work

Windows 10, python3.6

**Comment by vsilva89** [comment]
pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip

Collecting https://github.com/JonathanRaiman/glove/archive/master.zip
  Downloading https://github.com/JonathanRaiman/glove/archive/master.zip
     \ 102kB 1.1MB/s
Requirement already satisfied: cython in c:\users\victor.silvac\appdata\local\continuum\anaconda3\lib\site-packages (from glove==1.0.1) (0.28.2)
Requirement already satisfied: numpy in c:\users\victor.silvac\appdata\local\continuum\anaconda3\lib\site-packages (from glove==1.0.1) (1.15.4)
Building wheels for collected packages: glove
  Building wheel for glove (setup.py) ... done
  Stored in directory: C:\Users\VICTOR~1.SIL\AppData\Local\Temp\pip-ephem-wheel-cache-y332oud2\wheels\d8\f8\8d\8754c24e9f908071d7d0d903591b06d9915b56a491abaae45a
Successfully built glove
Installing collected packages: glove
Successfully installed glove-1.0.1


But when i type the import  "from glove import Glove"

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\glove\__init__.py", line 1, in <module>
    from .glove import Glove
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\glove\glove.py", line 8, in <module>
    from .glove_inner import train_glove
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyximport\pyximport.py", line 458, in load_module
    language_level=self.language_level)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\distutils\command\build_ext.py", line 558, in build_extension
    target_lang=language)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\distutils\ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "C:\Users\VICTOR.SILVAC\AppData\Local\Continuum\anaconda3\lib\distutils\_msvccompiler.py", line 522, in link
    raise LinkError(msg)
ImportError: Building module glove.glove_inner failed: ["distutils.errors.LinkError: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\BIN\\\\x86_amd64\\\\link.exe' failed with exit status 1104\n"]


Someone with a solution?

**Comment by namanchhikara** [comment]
(glove3) Namans-MacBook-Pro:~ namanchhikara$ pip install glove_python
Collecting glove_python
  Using cached https://files.pythonhosted.org/packages/3e/79/7e7e548dd9dcb741935d031117f4bed133276c2a047aadad42f1552d1771/glove_python-0.1.0.tar.gz
Collecting numpy (from glove_python)
  Downloading https://files.pythonhosted.org/packages/93/0e/30aaa357c3065957344b240482818eef31d4080f73dfa5f1ef7dcd8744d2/numpy-1.16.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 1.2MB/s 
Collecting scipy (from glove_python)
  Downloading https://files.pythonhosted.org/packages/f4/b1/6e0c995d7646b12112a721e93dc6316409cc4827c10ee309747f45ea6bfd/scipy-1.2.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.4MB)
    100% |████████████████████████████████| 27.4MB 534kB/s 
Building wheels for collected packages: glove-python
  Building wheel for glove-python (setup.py) ... error
  Complete output from command /Users/namanchhikara/anaconda3/envs/glove3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-install-x6dnrfqa/glove-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-wheel-3blf1cen --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/glove
  copying glove/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/glove
  copying glove/glove.py -> build/lib.macosx-10.7-x86_64-3.6/glove
  copying glove/corpus.py -> build/lib.macosx-10.7-x86_64-3.6/glove
  running build_ext
  building 'glove.glove_cython' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/glove
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/namanchhikara/anaconda3/envs/glove3/include -arch x86_64 -I/Users/namanchhikara/anaconda3/envs/glove3/include -arch x86_64 -I/Users/namanchhikara/anaconda3/envs/glove3/include/python3.6m -c glove/glove_cython.c -o build/temp.macosx-10.7-x86_64-3.6/glove/glove_cython.o -fopenmp -ffast-math
  clang: error: unsupported option '-fopenmp'
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for glove-python
  Running setup.py clean for glove-python
  Complete output from command /Users/namanchhikara/anaconda3/envs/glove3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-install-x6dnrfqa/glove-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: option --all not recognized
  
  ----------------------------------------
  Failed cleaning build dir for glove-python
Failed to build glove-python
Installing collected packages: numpy, scipy, glove-python
  Running setup.py install for glove-python ... error
    Complete output from command /Users/namanchhikara/anaconda3/envs/glove3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-install-x6dnrfqa/glove-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-record-swwlq9_m/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'glove.glove_cython' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/namanchhikara/anaconda3/envs/glove3/include -arch x86_64 -I/Users/namanchhikara/anaconda3/envs/glove3/include -arch x86_64 -I/Users/namanchhikara/anaconda3/envs/glove3/include/python3.6m -c glove/glove_cython.c -o build/temp.macosx-10.7-x86_64-3.6/glove/glove_cython.o -fopenmp -ffast-math
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/namanchhikara/anaconda3/envs/glove3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-install-x6dnrfqa/glove-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-record-swwlq9_m/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/wd/1g1n84q56b79gmp29cq91d5w0000gn/T/pip-install-x6dnrfqa/glove-python/

Facing similar issue. Any solution?

**Comment by AdithyaYelloju** [comment]
"pip3 install glove" given error. So I tried with "pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip". It installed successfully but this package does not have Corpus means When I try to import Corpus using "from glove import Corpus", it showed this error "ImportError: cannot import name 'Corpus' ". I uninstalled that one too. Finally tried "pip install glove_python". It worked!!
I am using Python 3.6.7.

**Comment by landist** [comment]
try pip install glove today in win 10 python 3.7,
failed as the same error as shown in previously poasted on 5 Jul 2018

**Comment by michaelbbryan** [comment]
Same issue as @AdithyaYelloju above.
Looks like the install succeeds but the first import glove causes a failure.

```
C:\> pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip
Collecting https://github.com/JonathanRaiman/glove/archive/master.zip
  Downloading https://github.com/JonathanRaiman/glove/archive/master.zip
     - 10kB ...
Requirement already satisfied: cython in c:\users\micha\anaconda3\lib\site-packages (from glove==1.0.1) (0.29.10)
Requirement already satisfied: numpy in c:\users\micha\anaconda3\lib\site-packages (from glove==1.0.1) (1.16.4)
Building wheels for collected packages: glove
  Building wheel for glove (setup.py) ... done
  Stored in directory: C:\Users\micha\AppData\Local\Temp\pip-ephem-wheel-cache-6zfryt56\wheels\d8\f8\8d\8754c24e9f908071d7d0d903591b06d9915b56a491abaae45a
Successfully built glove
Installing collected packages: glove
Successfully installed glove-1.0.1

(base) C:\Users\micha\Documents>python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import glove
C:\Users\micha\Anaconda3\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\micha\Anaconda3\lib\site-packages\glove\glove_inner.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
glove_inner.c
c:\users\micha\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\pyrex\glove\glove_inner.c(2288): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
glove_inner.obj : warning LNK4197: export 'PyInit_glove_inner' specified multiple times; using first specification
   Creating library C:\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\pyrex\glove\glove_inner.cp36-win_amd64.lib and object C:\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\pyrex\glove\glove_inner.cp36-win_amd64.exp
Generating code
Finished generating code
>>> glove.Corpus()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'glove' has no attribute 'Corpus'
```

**Comment by akshay13051994** [comment]
@michaelbbryan I am getting the same error. I can not import corpus from glove.
Did you find any solution? 
Please help me to solve the same Problem. 
Thank you in advance.

**Comment by michaelbbryan** [comment]
I struggled to get Visual C++ installed under Windows and then found a way out.
I installed Ubuntu for Windows and approached the problem in a Linux.
    installing python3 .... 
    and pip install glove==1.0.0

Then it worked.
Proved lucky as I need to move the model to a large server on AWS which is Ubuntu based.

**Comment by mytuphan** [comment]
> "pip3 install glove" given error. So I tried with "pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip". It installed successfully but this package does not have Corpus means When I try to import Corpus using "from glove import Corpus", it showed this error "ImportError: cannot import name 'Corpus' ". I uninstalled that one too. Finally tried "pip install glove_python". It worked!!
> I am using Python 3.6.7.

Hello, I am very new at this. Can you please advise how I can uninstalled this after installing "pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip"?

Thank you

**Comment by raghada** [comment]
You can just run `pip uninstall glove`

**Comment by willlling** [comment]
> Same issue as @AdithyaYelloju above.
> Looks like the install succeeds but the first import glove causes a failure.
> 
> ```
> C:\> pip3 install https://github.com/JonathanRaiman/glove/archive/master.zip
> Collecting https://github.com/JonathanRaiman/glove/archive/master.zip
>   Downloading https://github.com/JonathanRaiman/glove/archive/master.zip
>      - 10kB ...
> Requirement already satisfied: cython in c:\users\micha\anaconda3\lib\site-packages (from glove==1.0.1) (0.29.10)
> Requirement already satisfied: numpy in c:\users\micha\anaconda3\lib\site-packages (from glove==1.0.1) (1.16.4)
> Building wheels for collected packages: glove
>   Building wheel for glove (setup.py) ... done
>   Stored in directory: C:\Users\micha\AppData\Local\Temp\pip-ephem-wheel-cache-6zfryt56\wheels\d8\f8\8d\8754c24e9f908071d7d0d903591b06d9915b56a491abaae45a
> Successfully built glove
> Installing collected packages: glove
> Successfully installed glove-1.0.1
> 
> (base) C:\Users\micha\Documents>python
> Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import glove
> C:\Users\micha\Anaconda3\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\micha\Anaconda3\lib\site-packages\glove\glove_inner.pyx
>   tree = Parsing.p_module(s, pxd, full_module_name)
> glove_inner.c
> c:\users\micha\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
> C:\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\pyrex\glove\glove_inner.c(2288): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
> glove_inner.obj : warning LNK4197: export 'PyInit_glove_inner' specified multiple times; using first specification
>    Creating library C:\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\pyrex\glove\glove_inner.cp36-win_amd64.lib and object C:\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\Users\micha\.pyxbld\temp.win-amd64-3.6\Release\pyrex\glove\glove_inner.cp36-win_amd64.exp
> Generating code
> Finished generating code
> >>> glove.Corpus()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'glove' has no attribute 'Corpus'
> ```

U can try this:

1：git clone https://github.com/maciejkula/glove-python.git
2：open setup.py，then change “libraries=[‘stdc++’]” to “libraries=[]”
3：conda install cython
4：python setup.py install

**Comment by gmihran** [comment]
I also had the same problem. The problem was solved when I installed as follows.

pip install glove-python-binary
